vich_uploader:
    db_driver: orm

    mappings:
        tiny_images:
            uri_prefix: '%tiny_images%'
            upload_destination: '%kernel.project_dir%/public%tiny_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        top_image:
            uri_prefix: '%top_image%'
            upload_destination: '%kernel.project_dir%/public%top_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
